# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server CI

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'


jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js 
      uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'
          
    - name: Install dependencies
      working-directory: ./server
      run: npm ci
      
    - name: Build
      working-directory: ./server
      run: npm run build

    - name: Docker Setup Buildx
      working-directory: ./server
      uses: docker/setup-buildx-action@v3.10.0

    - name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.3.0
      with:
          username: avishka007
          password: ${{ secrets.DOCKER_HUB_TOKEN }} 
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with: 
          context: ./server
          push: ${{ github.event_name != 'pull_request' }}
          tags: avishka007/minimalist-docs-server:latest

          

          

